# Generated by Django 3.0.1 on 2019-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=20, verbose_name='性别')),
                ('user_city', models.CharField(choices=[('上海', '上海'), ('北京', '北京'), ('上海', '上海')], max_length=20, verbose_name='城市')),
                ('user_pass', models.CharField(max_length=200, verbose_name='密码')),
                ('user_hobby', models.CharField(choices=[('音乐', '音乐'), ('武术', '武术'), ('电玩', '电玩')], max_length=10, verbose_name='IT受理人员')),
            ],
        ),
    ]
