# Generated by Django 3.0.1 on 2019-12-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user_city',
            field=models.CharField(max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user_hobby',
            field=models.CharField(max_length=10, verbose_name='IT受理人员'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user_sex',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
    ]
