# Generated by Django 3.0.1 on 2020-01-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0003_auto_20191224_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_pass',
            new_name='user_path',
        ),
    ]
