# Generated by Django 3.0.1 on 2020-01-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0004_auto_20200103_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_path',
            new_name='user_filename',
        ),
        migrations.AddField(
            model_name='upload',
            name='user_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
