# Generated by Django 3.0.1 on 2020-01-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0005_auto_20200106_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user_name_new',
            field=models.CharField(default='', max_length=20),
        ),
    ]
