# Generated by Django 3.0.1 on 2020-01-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0006_upload_user_name_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_name_new',
            new_name='user_name_old',
        ),
    ]
