# Generated by Django 3.0.1 on 2020-01-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0007_auto_20200109_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='user_name_old',
            new_name='user_nickname',
        ),
    ]
