# Generated by Django 3.0.1 on 2020-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinaceNote', '0008_auto_20200109_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user_role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
